[build]
  base    = "react-front-end/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://kintsugi-app.herokuapp.com/"
  REACT_APP_WEBSOCKET_URL = "wss://kintsugi-app.herokuapp.com/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

  